# Generated by Django 6.0.2 on 2026-02-09 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='foto',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='poster',
            field=models.TextField(blank=True),
        ),
    ]
