# Generated by Django 6.0.2 on 2026-02-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_director_foto_pelicula_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='director',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
